---
title: "ML-EDA"
author: "Yingyao Gong, Yulu He, Zichuan Yu"
date: "2024-04-29"
output: pdf_document
---
```{r}
library(visdat)
library(ggplot2)
library(factoextra)
```


```{r}
data <- read.csv("data.csv")

head(data)
```

- DATA CLEANING

```{r}
any(is.na(data))
```

```{r}
vis_miss(data)
```

```{r}
names(data)
```


```{r}
data2 <- subset(data,select= - c(X))
any(is.na(data2))
```

```{r}
head(data2)
```

```{r}
# Histograms for numeric variables
numeric_vars <- sapply(data2, is.numeric)
hist_data <- data2[, numeric_vars]
par(mfrow = c(3, 4)) 
for (i in colnames(hist_data)) {
  hist(hist_data[[i]], main = paste("Histogram of", i), xlab = i, col = "blue")
}

# For outliers
boxplot(hist_data, las = 2, par(cex.axis = 0.8), main = "Boxplots for Numerical Variables")

# Bivariable analysis
ggplot(data2, aes(x = radius_mean, y = texture_mean)) +
  geom_point() +
  labs(title = "Scatter plot of radius_mean vs texture_mean", x = "radius_mean", y = "texture_mean")

# Correlation matrix
correlations <- cor(hist_data, use = "complete.obs")  # use "complete.obs" to handle missing values
corrplot::corrplot(correlations, method = "circle")
dev.off()

# Categorical variables
if ("diagnosis" %in% colnames(data2) && is.factor(data2$diagnosis)) {
  ggplot(data2, aes(x = diagnosis)) +
    geom_bar(fill = "skyblue") +
    labs(title = "Bar Plot of Diagnosis", x = "Diagnosis", y = "Frequency")
}
```
